logging:
  level:
    root: info

# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://39.100.136.2:3306/see
    username: root
    password: 123456qqaa
    driver-class-name: com.mysql.cj.jdbc.Driver

    # HikariCP连接池配置
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: MyHikariCP
